// @vitest-environment node
import { spawn, type ChildProcess } from "node:child_process"
import { createServer } from "node:net"
import { Surreal } from "surrealdb"
import { extractId } from "@/types/surreal-records"
import fixtures from "./task-search-fixtures.json"
import { buildTaskSearch, buildWorkflowSearch } from "./task-search"

const WIDE_RANGE = { from: "2000-01-01T00:00:00Z", to: "2100-01-01T00:00:00Z" }

interface FixtureRecord {
  id: string
  [field: string]: unknown
}

describe("task search against SurrealDB", () => {
  let db: Surreal
  let databaseProcess: ChildProcess

  beforeAll(async () => {
    const port = await new Promise<number>((resolve, reject) => {
      const socket = createServer()
      socket.on("error", reject)
      socket.listen(0, "127.0.0.1", () => {
        const address = socket.address()
        if (!address || typeof address === "string") return reject(new Error("No local port available"))
        socket.close(() => resolve(address.port))
      })
    })
    databaseProcess = spawn(
      "surreal",
      ["start", "--bind", `127.0.0.1:${port}`, "--user", "root", "--pass", "root", "memory"],
      { stdio: "ignore" },
    )
    let failure: Error | undefined
    databaseProcess.on("error", (error) => {
      failure = error
    })
    let healthy = false
    for (let attempt = 0; attempt < 100 && !healthy; attempt++) {
      if (failure) throw failure
      try {
        healthy = (await fetch(`http://127.0.0.1:${port}/health`)).ok
      } catch {
        await new Promise((resolve) => setTimeout(resolve, 50))
      }
    }
    if (!healthy) throw new Error("SurrealDB did not start")
    db = new Surreal()
    await db.connect(`ws://127.0.0.1:${port}/rpc`)
    await db.signin({ username: "root", password: "root" })
    await db.use({ namespace: "test", database: "search" })
    // Rows come from task-search-fixtures.json, generated by tooling/generate-task-search-fixtures.py with
    // Celery's saferepr and Python's repr, the two formats that reach the kwargs column.
    for (const { id, format: _format, ...content } of fixtures.tasks as FixtureRecord[]) {
      await db.query("CREATE type::record('task', $id) CONTENT $content", { id, content })
    }
    for (const { id, ...content } of fixtures.workflows as FixtureRecord[]) {
      await db.query("CREATE type::record('workflow', $id) CONTENT $content", { id, content })
    }
    await db.query("UPDATE task SET last_updated = time::now(); UPDATE workflow SET last_updated = time::now();")
  })

  afterAll(async () => {
    await db?.close()
    databaseProcess?.kill()
  })

  it.each(fixtures.queries.map((vector) => [vector.query, vector.expected] as const))(
    "finds %s",
    async (query, expected) => {
      const { clause, bindings } = buildTaskSearch(query)
      const [rows] = await db.query<[{ id: unknown }[]]>(`SELECT id FROM task WHERE (${clause})`, bindings)
      expect(rows.map((row) => extractId(row.id)).sort()).toEqual(expected)
    },
  )

  it.each(fixtures.workflowQueries.map((vector) => [vector.query, vector.expected] as const))(
    "finds workflows for %s",
    async (query, expected) => {
      const { prelude, clause, bindings } = buildWorkflowSearch(query)
      const [, , rows] = await db.query<[null, null, { id: unknown }[]]>(
        `${prelude.join("")}SELECT id FROM workflow WHERE (${clause})`,
        { ...bindings, ...WIDE_RANGE },
      )
      expect(rows.map((row) => extractId(row.id)).sort()).toEqual(expected)
    },
  )

  it("ignores member tasks of workflows outside the time range", async () => {
    const { prelude, clause, bindings } = buildWorkflowSearch("organization_id=1")
    const [, , rows] = await db.query<[null, null, { id: unknown }[]]>(
      `${prelude.join("")}SELECT id FROM workflow WHERE (${clause})`,
      { ...bindings, from: "2000-01-01T00:00:00Z", to: "2000-01-02T00:00:00Z" },
    )
    expect(rows).toEqual([])
  })
})

describe("buildTaskSearch", () => {
  it("falls back to plain text when the literal would exceed the regex size limit", () => {
    const { clause, bindings } = buildTaskSearch(`items=[${Array(20_000).fill('"item"').join(",")}]`)
    expect(bindings.kwargsPattern).toBeUndefined()
    expect(clause).not.toContain("string::matches")
  })

  it("falls back to plain text when the literal nests too deeply", () => {
    const { clause, bindings } = buildTaskSearch(`items=${"[".repeat(600)}0${"]".repeat(600)}`)
    expect(bindings.kwargsPattern).toBeUndefined()
    expect(clause).not.toContain("string::matches")
  })
})
