[tool.poetry]
name = "Celery Insights"
version = "0.2.0"
description = "Modern Real-Time Monitor for Celery"
authors = ["Dan Yishai <danyi1212@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
python-dotenv = "^1.0.0"
uvicorn = "^0.24.0"
celery = { version = "^5.3.6", extras = [
    "arangodb",
    "auth",
    "couchdb",
    "consul",
    "dynamodb",
    "elasticsearch",
    "eventlet",
    "gevent",
    "msgpack",
    "pymemcache",
    "pyro",
    "redis",
    "riak",
    "s3",
    "slmq",
    "sqlalchemy",
    "tblib",
    "zookeeper",
] }
websockets = "^12.0"
fastapi-cache2 = "^0.2.1"
user-agents = "^2.2.0"
aiopath = "^0.6.11"
pydantic = "^2.5.2"
pydantic-settings = "^2.1.0"
colorlog = "^6.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"
pytest-xdist = "^3.2.1"
pytest-mock = "^3.10.0"
pytest-asyncio = "^0.21.0"
pytest-env = "^0.8.1"
pytest-cov = "^4.0.0"
polyfactory = "^2.0.0a1"
ruff = "^0.0.261"
ipython = "^8.14.0"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "server"
log_cli_level = "INFO"

[tool.ruff]
line-length = 120
src = ["server"]
select = [
    "E", # pycodestyle
    "W", # pycodestyle
    "F", # pyflakes
    "N", # pep8
    "BLE", # flake8 blind except
    "FBT", # flake8 boolean trap
    "B", # flake8 bug bear
    "C4", # flake8 comprehensions
    "PIE", # flake8 pie
    "T20", # flake8 print
    "SIM", # flake8 simplify
    "ARG", # flake8 unused arguments
    "PTH", # flake8 pathlib
    "UP", # pyupgrade
    "ERA", # comment out code
    "PD", # pandas
    "RUF", # ruff rules
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
