[tool.poetry]
name = "Celery Insights"
version = "0.1.0"
description = "Modern Real-Time Monitor for Celery"
authors = ["Dan Yishai <danyi1212@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.94.0"
python-dotenv = "^1.0.0"
uvicorn = "^0.21.0"
celery = { extras = ["redis"], version = "^5.2.7" }
websockets = "^10.4"
fastapi-cache2 = "^0.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.3.0"
pytest-xdist = "^3.2.1"
pytest-mock = "^3.10.0"
pytest-asyncio = "^0.21.0"
pytest-env = "^0.8.1"
pytest-cov = "^4.0.0"
polyfactory = "^2.0.0a1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "server"
env = [
    "BROKER=amqp://guest:guest@localhost/",
    "RESULT_BACKEND=redis://localhost",
]