/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Raw_eventsRouteImport } from './routes/raw_events'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers.$workerId'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Raw_eventsRoute = Raw_eventsRouteImport.update({
  id: '/raw_events',
  path: '/raw_events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/explorer': typeof ExplorerRoute
  '/raw_events': typeof Raw_eventsRoute
  '/settings': typeof SettingsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/explorer': typeof ExplorerRoute
  '/raw_events': typeof Raw_eventsRoute
  '/settings': typeof SettingsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/explorer': typeof ExplorerRoute
  '/raw_events': typeof Raw_eventsRoute
  '/settings': typeof SettingsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/explorer'
    | '/raw_events'
    | '/settings'
    | '/tasks/$taskId'
    | '/workers/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/explorer'
    | '/raw_events'
    | '/settings'
    | '/tasks/$taskId'
    | '/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/explorer'
    | '/raw_events'
    | '/settings'
    | '/tasks/$taskId'
    | '/workers/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ExplorerRoute: typeof ExplorerRoute
  Raw_eventsRoute: typeof Raw_eventsRoute
  SettingsRoute: typeof SettingsRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw_events': {
      id: '/raw_events'
      path: '/raw_events'
      fullPath: '/raw_events'
      preLoaderRoute: typeof Raw_eventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ExplorerRoute: ExplorerRoute,
  Raw_eventsRoute: Raw_eventsRoute,
  SettingsRoute: SettingsRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
