/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Raw_eventsRouteImport } from './routes/raw_events'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentationIndexRouteImport } from './routes/documentation.index'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers.$workerId'
import { Route as TasksCompareRouteImport } from './routes/tasks.compare'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as DocumentationSetupRouteImport } from './routes/documentation.setup'
import { Route as DocumentationProductionNotesRouteImport } from './routes/documentation.production-notes'
import { Route as DocumentationKubernetesRouteImport } from './routes/documentation.kubernetes'
import { Route as DocumentationDeploymentPatternsRouteImport } from './routes/documentation.deployment-patterns'
import { Route as DocumentationConfigurationRouteImport } from './routes/documentation.configuration'
import { Route as DocumentationCeleryClustersRouteImport } from './routes/documentation.celery-clusters'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Raw_eventsRoute = Raw_eventsRouteImport.update({
  id: '/raw_events',
  path: '/raw_events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentationRoute,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCompareRoute = TasksCompareRouteImport.update({
  id: '/tasks/compare',
  path: '/tasks/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationSetupRoute = DocumentationSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DocumentationRoute,
} as any)
const DocumentationProductionNotesRoute =
  DocumentationProductionNotesRouteImport.update({
    id: '/production-notes',
    path: '/production-notes',
    getParentRoute: () => DocumentationRoute,
  } as any)
const DocumentationKubernetesRoute = DocumentationKubernetesRouteImport.update({
  id: '/kubernetes',
  path: '/kubernetes',
  getParentRoute: () => DocumentationRoute,
} as any)
const DocumentationDeploymentPatternsRoute =
  DocumentationDeploymentPatternsRouteImport.update({
    id: '/deployment-patterns',
    path: '/deployment-patterns',
    getParentRoute: () => DocumentationRoute,
  } as any)
const DocumentationConfigurationRoute =
  DocumentationConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DocumentationRoute,
  } as any)
const DocumentationCeleryClustersRoute =
  DocumentationCeleryClustersRouteImport.update({
    id: '/celery-clusters',
    path: '/celery-clusters',
    getParentRoute: () => DocumentationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/raw_events': typeof Raw_eventsRoute
  '/settings': typeof SettingsRoute
  '/documentation/celery-clusters': typeof DocumentationCeleryClustersRoute
  '/documentation/configuration': typeof DocumentationConfigurationRoute
  '/documentation/deployment-patterns': typeof DocumentationDeploymentPatternsRoute
  '/documentation/kubernetes': typeof DocumentationKubernetesRoute
  '/documentation/production-notes': typeof DocumentationProductionNotesRoute
  '/documentation/setup': typeof DocumentationSetupRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/compare': typeof TasksCompareRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/documentation/': typeof DocumentationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/explorer': typeof ExplorerRoute
  '/raw_events': typeof Raw_eventsRoute
  '/settings': typeof SettingsRoute
  '/documentation/celery-clusters': typeof DocumentationCeleryClustersRoute
  '/documentation/configuration': typeof DocumentationConfigurationRoute
  '/documentation/deployment-patterns': typeof DocumentationDeploymentPatternsRoute
  '/documentation/kubernetes': typeof DocumentationKubernetesRoute
  '/documentation/production-notes': typeof DocumentationProductionNotesRoute
  '/documentation/setup': typeof DocumentationSetupRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/compare': typeof TasksCompareRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/documentation': typeof DocumentationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/raw_events': typeof Raw_eventsRoute
  '/settings': typeof SettingsRoute
  '/documentation/celery-clusters': typeof DocumentationCeleryClustersRoute
  '/documentation/configuration': typeof DocumentationConfigurationRoute
  '/documentation/deployment-patterns': typeof DocumentationDeploymentPatternsRoute
  '/documentation/kubernetes': typeof DocumentationKubernetesRoute
  '/documentation/production-notes': typeof DocumentationProductionNotesRoute
  '/documentation/setup': typeof DocumentationSetupRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/compare': typeof TasksCompareRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/documentation/': typeof DocumentationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/documentation'
    | '/explorer'
    | '/raw_events'
    | '/settings'
    | '/documentation/celery-clusters'
    | '/documentation/configuration'
    | '/documentation/deployment-patterns'
    | '/documentation/kubernetes'
    | '/documentation/production-notes'
    | '/documentation/setup'
    | '/tasks/$taskId'
    | '/tasks/compare'
    | '/workers/$workerId'
    | '/documentation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/explorer'
    | '/raw_events'
    | '/settings'
    | '/documentation/celery-clusters'
    | '/documentation/configuration'
    | '/documentation/deployment-patterns'
    | '/documentation/kubernetes'
    | '/documentation/production-notes'
    | '/documentation/setup'
    | '/tasks/$taskId'
    | '/tasks/compare'
    | '/workers/$workerId'
    | '/documentation'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/documentation'
    | '/explorer'
    | '/raw_events'
    | '/settings'
    | '/documentation/celery-clusters'
    | '/documentation/configuration'
    | '/documentation/deployment-patterns'
    | '/documentation/kubernetes'
    | '/documentation/production-notes'
    | '/documentation/setup'
    | '/tasks/$taskId'
    | '/tasks/compare'
    | '/workers/$workerId'
    | '/documentation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DocumentationRoute: typeof DocumentationRouteWithChildren
  ExplorerRoute: typeof ExplorerRoute
  Raw_eventsRoute: typeof Raw_eventsRoute
  SettingsRoute: typeof SettingsRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksCompareRoute: typeof TasksCompareRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw_events': {
      id: '/raw_events'
      path: '/raw_events'
      fullPath: '/raw_events'
      preLoaderRoute: typeof Raw_eventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/compare': {
      id: '/tasks/compare'
      path: '/tasks/compare'
      fullPath: '/tasks/compare'
      preLoaderRoute: typeof TasksCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/setup': {
      id: '/documentation/setup'
      path: '/setup'
      fullPath: '/documentation/setup'
      preLoaderRoute: typeof DocumentationSetupRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/production-notes': {
      id: '/documentation/production-notes'
      path: '/production-notes'
      fullPath: '/documentation/production-notes'
      preLoaderRoute: typeof DocumentationProductionNotesRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/kubernetes': {
      id: '/documentation/kubernetes'
      path: '/kubernetes'
      fullPath: '/documentation/kubernetes'
      preLoaderRoute: typeof DocumentationKubernetesRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/deployment-patterns': {
      id: '/documentation/deployment-patterns'
      path: '/deployment-patterns'
      fullPath: '/documentation/deployment-patterns'
      preLoaderRoute: typeof DocumentationDeploymentPatternsRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/configuration': {
      id: '/documentation/configuration'
      path: '/configuration'
      fullPath: '/documentation/configuration'
      preLoaderRoute: typeof DocumentationConfigurationRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/documentation/celery-clusters': {
      id: '/documentation/celery-clusters'
      path: '/celery-clusters'
      fullPath: '/documentation/celery-clusters'
      preLoaderRoute: typeof DocumentationCeleryClustersRouteImport
      parentRoute: typeof DocumentationRoute
    }
  }
}

interface DocumentationRouteChildren {
  DocumentationCeleryClustersRoute: typeof DocumentationCeleryClustersRoute
  DocumentationConfigurationRoute: typeof DocumentationConfigurationRoute
  DocumentationDeploymentPatternsRoute: typeof DocumentationDeploymentPatternsRoute
  DocumentationKubernetesRoute: typeof DocumentationKubernetesRoute
  DocumentationProductionNotesRoute: typeof DocumentationProductionNotesRoute
  DocumentationSetupRoute: typeof DocumentationSetupRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
}

const DocumentationRouteChildren: DocumentationRouteChildren = {
  DocumentationCeleryClustersRoute: DocumentationCeleryClustersRoute,
  DocumentationConfigurationRoute: DocumentationConfigurationRoute,
  DocumentationDeploymentPatternsRoute: DocumentationDeploymentPatternsRoute,
  DocumentationKubernetesRoute: DocumentationKubernetesRoute,
  DocumentationProductionNotesRoute: DocumentationProductionNotesRoute,
  DocumentationSetupRoute: DocumentationSetupRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
}

const DocumentationRouteWithChildren = DocumentationRoute._addFileChildren(
  DocumentationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DocumentationRoute: DocumentationRouteWithChildren,
  ExplorerRoute: ExplorerRoute,
  Raw_eventsRoute: Raw_eventsRoute,
  SettingsRoute: SettingsRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksCompareRoute: TasksCompareRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
