name: Run eslint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        cache: "npm"
        cache-dependency-path: "frontend/package-lock.json"
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
